version: "3.9"

services:
  web:
    build:
      context: ../..
      dockerfile: deploy/lightsail/Dockerfile
    command: ["gunicorn", "-b", "0.0.0.0:5000", "app:create_app()"]
    env_file:
      - ../../config/lightsail.env
    ports:
      - "5001:5000"
    restart: unless-stopped
